"""User contacts

Revision ID: e908fde3f956
Revises: fe9642e7d89d
Create Date: 2026-03-23 21:42:13.146099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e908fde3f956'
down_revision: Union[str, Sequence[str], None] = 'fe9642e7d89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_id', name='uq_user_contacts_user_id_contact_id')
    )
    op.create_index(op.f('ix_user_contacts_contact_id'), 'user_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_user_contacts_user_id'), 'user_contacts', ['user_id'], unique=False)
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_contacts_user_id'), table_name='user_contacts')
    op.drop_index(op.f('ix_user_contacts_contact_id'), table_name='user_contacts')
    op.drop_table('user_contacts')
    # ### end Alembic commands ###
